spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678

mybatis:
  type-aliases-package: com.caopeng.travel.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.caopeng.travel.mapper : debug

server:
  port: 8080